/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32c031xx.h"
#include "stm32c0xx.h"
#include <stdint.h>
static void delay(volatile uint32_t count) {
  while (count > 0) /* Blank 1 */
  {
    __NOP();
    count--; /* Blank 2 */
  }
}
// int main(void) {
//   /* Enable the peripheral clock for GPIOA. */
//   RCC->IOPENR |= RCC_IOPENR_GPIOAEN; /* Blank 3 */

//   /* Configure PA5 as a general-purpose output. */
//   GPIOA->MODER &= ~GPIO_MODER_MODE5_Msk; /* Blank 4 */
//   GPIOA->MODER |= GPIO_MODER_MODE5_0; /* Blank 5 */

//   while (1) {
//     /* Set PA5 HIGH and wait. */
//     GPIOA->ODR |= GPIO_ODR_OD5; /* Blank 6 */
//     delay(200000);   /* Blank 7 */
    
//     /* Clear PA5 LOW and wait. */
//     GPIOA->ODR &= ~GPIO_ODR_OD5; /* Blank 8 */
//     delay(200000);   /* Blank 9 */
//   }
//   return 0; /* Blank 10 */
// }

static void Port_Clock_Enable(void)
{
  RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
}

int main(void) {
  Port_Clock_Enable();

  GPIOA->MODER &= ~(GPIO_MODER_MODE5_Msk | GPIO_MODER_MODE6_Msk | GPIO_MODER_MODE7_Msk);
  GPIOA->MODER |= (GPIO_MODER_MODE5_0 | GPIO_MODER_MODE6_0 | GPIO_MODER_MODE7_0);

  while (1) {
    GPIOA->ODR |= GPIO_ODR_OD5;
    delay(3000000);

    GPIOA->ODR &= ~GPIO_ODR_OD5;
    GPIOA->ODR |= GPIO_ODR_OD7;
    delay(3000000);

    GPIOA->ODR &= ~GPIO_ODR_OD7;
    GPIOA->ODR |= GPIO_ODR_OD6;
    delay(700000);
    GPIOA->ODR &= ~GPIO_ODR_OD6;
  }

  return 0;

}
