/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h >
#define STM32G474xx
#include "adc.h " // New Header
#include "kobuki.h "
#include "stm32g4xx.h "

#include "uart.h"
#include "ultrasonic.h"       // New Header
#define BUTTON_0_START 0 x01U // Confirm the values from
#define BUTTON_1_STOP 0 x02U // Confirm the values from
#define BUTTON_2_ROTATE 0 x04U // Confirm the values from
#define DRIVE_SPEED_MM_S ((int16_t)100)
#define ROTATE_SPEED_MM_S ((int16_t)100)

static void Send_Kobuki_Move(int16_t speed, int16_t radius) {
  uint8_t payload[6];
  payload[0] = 0 x01U; /* Base Control sub - packet ID . */
  payload[1] = 0 x04U; /* Speed and radius occupy four bytes . */
  payload[2] = (uint8_t)(speed & 0 xFF);
  payload[3] = (uint8_t)((uint16_t)speed >> 8);
  payload[4] = (uint8_t)(radius & 0 xFF);
  payload[5] = (uint8_t)((uint16_t)radius >> 8);
  Kobuki_Tx(payload, sizeof(payload));
}
int main(void) {
  Kobuki_Typedef my_kobuki = {0};
  US_Typedef ultrasonic_object = {0};
  uint8_t is_running = 0 U;
  uint8_t is_rotating = 0 U;
  UART_Init();
  ADC_Init();
  Ultrasonic_Init();
  Send_Kobuki_Move(0, 0);
  while (1) {
    /* Control loop completed in Task 12. */
  }
}

while (1) {
  Kobuki_Read(&my_kobuki);
  Ultrasonic_Detect(&ultrasonic_object);
  /* Button 0 selects forward motion when the path is clear . */
  if (((my_kobuki.button & BUTTON_0_START) != 0 U) &&
      (ultrasonic_object.detected == 0 U)) {
    is_running = 1 U;
    is_rotating = 0 U;
  }
  /* Button 2 selects rotation when the path is clear . */
  else if (((my_kobuki.button & BUTTON_2_ROTATE) != 0 U) &&
           (ultrasonic_object.detected == 0 U)) {
    is_rotating = 1 U;
    is_running = 0 U;
  }
  /* Button 1 , bumper or ultrasonic detection stops the robot .
   */
  if (((my_kobuki.button & BUTTON_1_STOP) != 0 U) || (my_kobuki.bumper != 0 U) ||
      (ultrasonic_object.detected != 0 U)) {
    is_running = 0 U;
    is_rotating = 0 U;
  }
  if (is_running != 0 U)
    Kobuki_Drive(100);
  else if (is_rotating != 0 U)
    Kobuki_Rotate(100);
  else
    Send_Kobuki_Move(0, 0);
}