/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32c031xx.h"
#include "stm32c0xx.h"
#include <stdint.h>

// define states
typedef enum
{
    PIN_LOW=0,
    PIN_HIGH=1
} PinState;

typedef enum
{
    MODE_INPUT=0,
    MODE_OUTPUT=1,
    MODE_ALT=2,
    MODE_ANALOG=3
} PinMode;

#define PULL_NONE 0
#define PULL_UP 1
#define PULL_DOWN 2

// wrappers
static void Port_Clock_Enable(void) {
    RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
    RCC->IOPENR |= RCC_IOPENR_GPIOBEN;
}

static void Pin_Mode(GPIO_TypeDef *port, uint8_t pin, PinMode mode) {
    uint32_t bit_position = (uint32_t)pin * 2U;
    port->MODER &= ~(0b11U << bit_position);
    port->MODER |= ((uint32_t)mode << bit_position);
}

static void Pin_Pull(GPIO_TypeDef *port, uint8_t pin, uint8_t pull) {
    uint32_t bit_position = (uint32_t)pin * 2U;
    port->PUPDR &= ~(0b11U << bit_position);
    port->PUPDR |= ((uint32_t)pull << bit_position);
}

static uint8_t Pin_Read(GPIO_TypeDef *port, uint8_t pin) {
    return (uint8_t)((port->IDR >> pin) & 1U);
}

static void Pin_Write(GPIO_TypeDef *port, uint8_t pin, PinState state){
    if (state==PIN_HIGH) {
        port->ODR |= (1U << pin);
    } else {
        port->ODR &= ~(1U << pin);
    }
}

static void Adc_Init(void) {
    RCC->APBENR2 |= (1U << 20);
    ADC1->ISR |= ADC_ISR_ADRDY;
    ADC1->CR |= ADC_CR_ADEN;

    while((ADC1->ISR & ADC_ISR_ADRDY) == 0) {
    }
}

static uint16_t Adc_Read(uint8_t channel) {
    ADC1->CHSELR = (1U << channel);
    ADC1->CR |= ADC_CR_ADSTART;
    while ((ADC1->ISR & ADC_ISR_EOC ) == 0) {
    }
    return (uint16_t)ADC1->DR;
}

// delay func
static void delay(volatile uint32_t count) {
    while (count>0){
        __NOP();
        count--;
    }
}

// main func
int main(void) {

    Port_Clock_Enable();
    Pin_Mode(GPIOB, 0U, MODE_OUTPUT);

    Pin_Mode(GPIOB, 1U, MODE_INPUT);
    Pin_Pull(GPIOB, 1U, PULL_UP);

    Pin_Mode(GPIOA, 5U, MODE_OUTPUT);

    Pin_Mode(GPIOA, 0U, MODE_ANALOG);
    Pin_Mode(GPIOA, 1U, MODE_ANALOG);

    Pin_Mode(GPIOA, 6U, MODE_INPUT);
    Pin_Pull(GPIOA, 6U, PULL_UP);

    Adc_Init();

    uint16_t horizontal;
    uint16_t vertical;
    uint32_t blink;

    while (1) {
        horizontal = Adc_Read(0);
        vertical = Adc_Read(1);

        if (Pin_Read(GPIOB, 1U) == 0) {
            Pin_Write(GPIOB, 0U, PIN_HIGH);

        } else {
            Pin_Write(GPIOB, 0U, PIN_LOW);
        }

        if (horizontal > 2600) {
            blink = 3000000; // l (7 counts)

        } else if (horizontal < 1500) {
            blink = 2000000; // r (5 counts)

        } else if (vertical > 2600) {
            blink = 1000000; // u (3 counts)

        } else if (vertical < 1500) {
            blink = 5000000; // d (10 counts)

        } else {
            blink = 0; // c
        }

        // led4 blink
        if (blink > 0) {
            Pin_Write(GPIOA, 5U, PIN_HIGH);
            delay(blink);
            Pin_Write(GPIOA, 5U, PIN_LOW);
            delay(blink);

        } else {
            if (Pin_Read(GPIOA, 6U) == 0) {
                Pin_Write(GPIOA, 5U, PIN_HIGH);
            } else {
                Pin_Write(GPIOA, 5U, PIN_LOW);
            }
        }
        delay(10000);
    }
    return 0;
}


