/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32g4xx.h"
#include "kobuki.h"
#include "uart.h"

int main(void) {
    UART_Init(); // Initiate UART
    Kobuki_Typedef my_kobuki = {0}; // Initiate a variable with Kobuki Typedef
                                     // that contains sensors reading

    // 0 = Stopped (Safe state), 1 = Running
    uint8_t is_running = 0;
    uint8_t is_rotating = 0;

    while (1) {
        // 1. Read the latest sensor data
        Kobuki_Read(&my_kobuki);

        // 2. Evaluate Start/Stop triggers
        if (my_kobuki.button == 0x01) { // DRIVE STATE
            is_running = 1;  // Start command received (Button 0). DRIVE STATE
            is_rotating = 0; // Switch off ROTATE STATE
        }
        else if (my_kobuki.button == 0x04) { // ROTATE STATE
            is_rotating = 1; // Start command received (Button 2). ROTATE STATE
            is_running = 0;  // Switch off DRIVE STATE
        }

        // Stop triggers take priority over start triggers. IDLE STATE
        if (my_kobuki.button == 0x02 || my_kobuki.bumper != 0) {
            is_running = 0;  // Stop command (Button 1) or collision detected. IDLE STATE
            is_rotating = 0;
        }

        // 3. Command the motors based on the current state
        if (is_running == 1) {
            Kobuki_Drive(100); // Drive forward at 100 mm/s. DRIVE STATE
        } else if (is_rotating == 1) {
            Kobuki_Rotate(100); // Rotate at 100 mm/s. ROTATE STATE
        } else {
            Kobuki_Drive(0); // Command zero velocity. IDLE STATE
        }

        // 4. Control loop delay
        for (volatile int i = 0; i < 50000; i++); // Shorter delay for quick
                                                    // recognition of button inputs
    }
}
