/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#define STM32G474xx
#include "stm32g4xx.h"
#include "uart.h"
#include "kobuki.h"

int main(void) {
  // Create a structure to store kobuki values :
  Kobuki_Typedef my_kobuki = {0};
  // Initialize system UART
  UART_Init();
  while (1) {
    // Read the full payload arriving at the RX pin and parse it
    Kobuki_Read(&my_kobuki);
    // Pause so you can inspect ’ my_kobuki ’ in your debugger
    for (volatile int i = 0; i < 500000; i++);
  }
}