/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32c031xx.h"
#include "stm32c0xx.h"
#include <stdint.h>

// define states
typedef enum
{
    PIN_LOW=0,
    PIN_HIGH=1
} PinState;

typedef enum
{
    MODE_INPUT=0,
    MODE_OUTPUT=1,
    MODE_ALT=2,
    MODE_ANALOG=3
} PinMode;

#define PULL_NONE 0
#define PULL_UP 1
#define PULL_DOWN 2

// wrappers
static void Port_Clock_Enable(void) {
    RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
    RCC->IOPENR |= RCC_IOPENR_GPIOBEN;
}

static void Pin_Mode(GPIO_TypeDef *port, uint8_t pin, PinMode mode) {
    uint32_t bit_position = (uint32_t)pin * 2U;
    port->MODER &= ~(0b11U << bit_position);
    port->MODER |= ((uint32_t)mode << bit_position);
}

static void Pin_Pull(GPIO_TypeDef *port, uint8_t pin, uint8_t pull) {
    uint32_t bit_position = (uint32_t)pin * 2U;
    port->PUPDR &= ~(0b11U << bit_position);
    port->PUPDR |= ((uint32_t)pull << bit_position);
}

static uint8_t Pin_Read(GPIO_TypeDef *port, uint8_t pin) {
    return (uint8_t)((port->IDR >> pin) & 1U);
}

static void Pin_Write(GPIO_TypeDef *port, uint8_t pin, PinState state){
    if (state==PIN_HIGH) {
        port->ODR |= (1U << pin);
    } else {
        port->ODR &= ~(1U << pin);
    }
}

int main(void) {

    while (1) {
    }
    return 0;
}
