/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code
 * Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32c031xx.h"
#include "stm32c0xx.h"
#include <stdint.h>

// define states
typedef enum { PIN_LOW = 0, PIN_HIGH = 1 } PinState;

typedef enum {
  MODE_INPUT = 0,
  MODE_OUTPUT = 1,
  MODE_ALT = 2,
  MODE_ANALOG = 3
} PinMode;

#define PULL_NONE 0
#define PULL_UP 1
#define PULL_DOWN 2

// wrappers
static void Port_Clock_Enable(void) {
  RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
}

static void Pin_Mode(GPIO_TypeDef *port, uint8_t pin, PinMode mode) {
  uint32_t bit_position = (uint32_t)pin * 2U;
  port->MODER &= ~(0b11U << bit_position);
  port->MODER |= ((uint32_t)mode << bit_position);
}

static void Pin_Pull(GPIO_TypeDef *port, uint8_t pin, uint8_t pull) {
  uint32_t bit_position = (uint32_t)pin * 2U;
  port->PUPDR &= ~(0b11U << bit_position);
  port->PUPDR |= ((uint32_t)pull << bit_position);
}

static uint8_t Pin_Read(GPIO_TypeDef *port, uint8_t pin) {
  return (uint8_t)((port->IDR >> pin) & 1U);
}

static void Pin_Write(GPIO_TypeDef *port, uint8_t pin, PinState state) {
  if (state == PIN_HIGH) {
    port->ODR |= (1U << pin);
  } else {
    port->ODR &= ~(1U << pin);
  }
}

// --- EXTI Wrappers ---
typedef enum { TRIG_RISING = 0, TRIG_FALLING = 1, TRIG_BOTH = 2 } ExtiTrigger;

void EXTI_Init(GPIO_TypeDef *port, uint8_t pin, ExtiTrigger trigger) {
  // 1. Establish the numerical port identifier
  uint32_t port_idx = 0;
  __________________;
  __________________;
  __________________;

  // 2. Configure the EXTI_EXTICRx Multiplexer
  // The STM32C0 allocates 8 bits per pin across 4 registers
  uint8_t register_index = pin / 4;
  uint8_t bit_position = (pin % 4) * 8;
  __________________;
  __________________;

  // 3. Configure Trigger Selection Registers : EXTI - > FTSR1 and EXTI - >
  // RTSR1
  if (trigger == TRIG_FALLING || trigger == TRIG_BOTH) {
    __________________;
  }
  if (trigger == TRIG_RISING || trigger == TRIG_BOTH) {
    __________________;
  }

  // 4. Unmask the designated interrupt line : EXTI - > IMR1
  __________________;
}

// Wrapper to set the Alternate Function of a pin
void Pin_AltFunc(GPIO_TypeDef *port, uint8_t pin, uint8_t af_number) {
  // AFR [0] handles pins 0 -7. AFR [1] handles pins 8 -15.
  // Each pin gets 4 bits to define its Alternate Function (0 to 15).
  if (pin < 8) {
    port->AFR[0] &= ~(0 xFUL << (pin * 4));                              //
    port->AFR[0] |= ((uint32_t)af_number << (pin * 4)); //
  }
  else {
    port->AFR[1] &= ~(0 xFUL << ((pin - 8) * 4));
    port->AFR[1] |= ((uint32_t)af_number << ((pin - 8) * 4));
  }
}
void PWM_Init(void) {
  // 1. Set PA8 to Alternate Function Mode (10)
  __________________;

  // 2. Route PA8 to TIM1_CH1 ( Alternate Function 2)
  __________________;

  // 3. Enable the TIM1 Clock
  __________________;

  // 4. Configure Timer Timing ( Assuming 48 MHz default system clock )
__________________ ; // Prescaler : we want 1 MHz
__________________; // Period : 20 ,000 ticks = 20

    // 5. Configure PWM Mode 1 on Channel 1
    // Clear output compare mode bits , then set to PWM mode 1 (110)
__________________;
__________________;
__________________; // Enable preload

// 6. Enable Channel 1 Output
__________________;

// 7. Main Output Enable ( for TIM1 )

__________________;
// 8. Start the Timer
__________________;
}

// Wrapper to easily set the pulse width
void PWM_SetWidth(uint16_t microseconds) { 
    TIM1->CCR1 = microseconds; 
}

int main(void) {

    Port_Clock_Enable();



  while (1) {
  }
  return 0;
}
