/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <sys/types.h>

ushort sqrtint(unsigned int x) {
   uint a = 0;
   uint b = 65535;
   uint mid = (a+b)/2;
   uint mid_prev = 0;

   while (mid != mid_prev) {
      if (mid*mid == x) {
         return (ushort)mid;
      }

      if ((mid*mid) < x) {
         a = mid;

      } else {
         b = mid;
      }
      mid_prev = mid;
      mid = (a+b)/2;
   }
   return (ushort)mid;
}

ushort isPrime(uint n) {
   if (n<=1) {
      return 0;
   }

   if (n == 2) {
      return 1;
   }

   uint i = 2;
   uint limit = sqrtint(n);

   while (1) {
      if (i<=limit) {

         if((n % i) == 0) {
            return 0;
         }
         i++;

      } else {
         return 1;
      }
   }
}

int main(void) {
   while(1) {
      ushort test_sqrt = sqrtint(25);
      test_sqrt = sqrtint(133);
      ushort test_prime = isPrime(9);
      test_prime = isPrime(7);
   }

   return 0;
}


