/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32c0xx.h"
#include "my_stm_helper.h"
#include "assignment_1.h"
#include "pwm_helper.h"

// CODE FROM ASSIGNMENT1.C:
volatile uint32_t lfsr_state = 0xA5A5A5A5;

void SysTick_Init(void){
    // Part of the Arm Cortex Peripherals. Not found in RM0490
    SysTick->LOAD = 0x00FFFFFF;
    SysTick->VAL  = 0;
    SysTick->CTRL = SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk;
}

// Subroutine to add faulty detections
ItemColour_t Apply_LFSR_Fault(ItemColour_t true_col) {
    lfsr_state = (lfsr_state >> 1) ^ (-(lfsr_state & 1u) & 0xD0000001u);

    if ((lfsr_state % 100) < 20) {
        return (ItemColour_t)((true_col % 3) + 1);
    }
    return true_col;
}

// Subroutine to generate item and sensor detection
void Generate_Next_Item(void) {
    lfsr_state ^= SysTick->VAL;
    truth_colour = (ItemColour_t)((lfsr_state % 3) + 1);
    sensor_colour = Apply_LFSR_Fault(truth_colour);
    Set_Truth_RGB(truth_colour);
    Set_Sensor_RGB(sensor_colour);
}

// GLOBAL VARIABLES:
// Globals used for generating item
volatile ItemColour_t truth_colour  = OFF;
volatile ItemColour_t sensor_colour = OFF;

// Global flags shared by interrupts
volatile uint8_t step_count = 0; // 0,1,2 for steps
volatile uint8_t item_active = 0; // 1 while an item is still in place
volatile uint8_t emer_stop = 0; // flag for emergency stop button

// FUNCTIONS TO DISPLAY COLOUR:
// Makes the true led display colour
void Set_Truth_RGB(ItemColour_t colour) {
    // turn all leds off first
    GPIO_OutputClearPin(GPIOA, 0); // r
    GPIO_OutputClearPin(GPIOA, 1); // g
    GPIO_OutputClearPin(GPIOA, 4); // b

    switch (colour) {
        case RED: // if red turn only PA0 on
            GPIO_OutputSetPin(GPIOA, 0);
            break;
        case GREEN: // if green turn only PA1 on
            GPIO_OutputSetPin(GPIOA, 1);
            break;
        case BLUE: // if blue turn only PA4 on
            GPIO_OutputSetPin(GPIOA, 4);
            break;
        default:
            break;
    }
}

// Makes the sensor led display colour
void Set_Sensor_RGB(ItemColour_t colour) {
    // turn all leds off first
    GPIO_OutputClearPin(GPIOA, 3);  // r
    GPIO_OutputClearPin(GPIOA, 11); // g
    GPIO_OutputClearPin(GPIOA, 8);  // b

    switch (colour) {
        case RED: // if red turn only PA3 on
            GPIO_OutputSetPin(GPIOA, 3);
            break;
        case GREEN: // if green turn only PA11 on
            GPIO_OutputSetPin(GPIOA, 11);
            break;
        case BLUE: // if blue turn only PA8 on
            GPIO_OutputSetPin(GPIOA, 8);
            break;
        default: 
            break;
    }
}

// HARDWARE INITIALISATION:
// Initialise all GPIO pins for input and output
void GPIO_Init(void) {
    Clock_Enable(GPIOA_BUS);
    Clock_Enable(GPIOB_BUS);

    // Fault led, PA9, output
    GPIO_InitPin(GPIOA, 9, OUTPUT, NONE);

    // Real colour led, PA0(r), PA1(g), PA4(b)
    GPIO_InitPin(GPIOA, 0, OUTPUT, NONE);
    GPIO_InitPin(GPIOA, 1, OUTPUT, NONE);
    GPIO_InitPin(GPIOA, 4, OUTPUT, NONE);

    // Sensed colour led,PA3(r), PA11(g), PA8(b)
    GPIO_InitPin(GPIOA, 3, OUTPUT, NONE);
    GPIO_InitPin(GPIOA, 11, OUTPUT, NONE);
    GPIO_InitPin(GPIOA, 8, OUTPUT, NONE);

    // Buttons, inputs, pull down
    GPIO_InitPin(GPIOA, 2, INPUT, PULL_DOWN);  // new item
    GPIO_InitPin(GPIOA, 10, INPUT, PULL_DOWN); // step gate
    GPIO_InitPin(GPIOB, 5, INPUT, PULL_DOWN);  // emergency stop
}

// Initialise all EXTI lines
void EXTI_Init(void) {
    // pull down initialised so EXTI set for rising edge
    EXTI_InitPin(EXTI_GPIOA, 2, RISING, EXTI2_3_IRQn);   // new item
    EXTI_InitPin(EXTI_GPIOA, 10, RISING, EXTI4_15_IRQn); // step gate
    EXTI_InitPin(EXTI_GPIOB, 5, RISING, EXTI4_15_IRQn);  // emergency stop
}

// HELPERS FOR SORTING VIA GATES AND EMERGENCY STOPPING:
// Sorting function
void Gate_Helper(void) {
    if (!item_active) { // if item not in place, exit
        return;
    }

    switch (step_count) {
        case 0: // Stage 1, gate 1
            if (sensor_colour==BLUE) { // if blue, redirect to blue bin
                Gate1_SetWidth(ANTI_CLOCK); // 45 deg anti clockwise

            } else { // otherwise go to stage 2
                Gate1_SetWidth(CLOCK_WISE);  // 45 deg clockwise
            }
            step_count = 1; 
            break;

        case 1: // Stage 2, gate 2
            if (sensor_colour==GREEN) { // if green, rediret to green bin
                Gate2_SetWidth(ANTI_CLOCK); // 45 deg anti clockwise

            } else if (sensor_colour==RED) {  // if red, redirect to red bin
                Gate2_SetWidth(CLOCK_WISE); // 45 deg clockwise
            }
            step_count = 2;
            break;

        case 2: // Stage 3
            // both gates back to neutral
            Gate1_SetWidth(NEUTRAL);
            Gate2_SetWidth(NEUTRAL);

            // both leds off
            Set_Truth_RGB(OFF);
            Set_Sensor_RGB(OFF);

            // all flags reset
            truth_colour = OFF;
            sensor_colour = OFF;
            item_active = 0;
            step_count = 0;
            break;

        default:
            break;
    }
}

// Emergency button func, no need to restart whole system
void Emer_Stop(void) {
    GPIO_OutputSetPin(GPIOA, 9); // fault led on

    // both gates to neutral
    Gate1_SetWidth(NEUTRAL);
    Gate2_SetWidth(NEUTRAL);

    emer_stop = 1; // flag set to 1 to block new item and step gate
}

// ISR's:
// New item button (PA2)
void EXTI2_3_IRQHandler(void) {
    if (EXTI->RPR1 & (1 << 2)) { // check if isr called by pin 2
        EXTI->RPR1 = (1 << 2); // write 1 to clear

        if (!emer_stop && !item_active) {
            Generate_Next_Item(); // sets truth/sensor colour + lights led
            item_active = 1;
            step_count = 0;
        }
    }
}

// Step gate (PA10), Stop button(PB5)
void EXTI4_15_IRQHandler(void) {
    if (EXTI->RPR1 & (1 << 5)) { // check if isr called by pin 5
        EXTI->RPR1 = (1 << 5); // write 1 to clear
        Emer_Stop(); // call emergency button helper
    }

    if (EXTI->RPR1 & (1 << 10)) { // check if isr called by pin 10
        EXTI->RPR1 = (1 << 10); // write 1 to clear
        if (!emer_stop) {
            Gate_Helper(); // call the step gate helper
        }
    }
}

// MAIN FUNC:
int main(void) {
    // call all initialise funcions
    SysTick_Init();
    GPIO_Init();
    PWM_Init();
    EXTI_Init();

    while (1) {}
    return 0;
}
